#!/bin/zsh

# Transparency and fading
#compton -bf -i 0.8 --backend glx --vsync opengl-swc
# Right alt is considered mod4
xmodmap -e "keycode 108 = Super_L"
xmodmap -e "remove mod1 = Super_L"
# Power button is Insert
xmodmap -e "keycode 124 = Insert"
# Disable touchpad while typing
# https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Using_.xinitrc
syndaemon -t -k -i 2 &
# Disable middle click
synclient TapButton2=-1
# Pressure required for movement
synclient FingerHigh=45
# Speed
synclient MaxSpeed=3
# Two finger horizontal scrolling
synclient HorizTwoFingerScroll=1
# "Natural" scrolling
synclient HorizScrollDelta=-109
synclient VertScrollDelta=-109
# Locked drags because mac touchpads are stupid
synclient LockedDrags=1
synclient LockedDragTimeout=2000
# Startup processes
parcellite &
xbindkeys &
qiv -xrt ~/pictures/bg/ &

while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
