#!/bin/sh

if [ ! -S /tmp/ssh-irc ] && [ $DISPLAY ]; then
	SSH_ASKPASS=askpass.sh setsid ssh $* -fMNS /tmp/ssh-irc
	while ( [ ! -S /tmp/ssh-irc ] ); do
		sleep 1
	done
fi

if [ $DISPLAY ]; then
	/usr/bin/st -c ircterm -T ircterm ssh $* -S /tmp/ssh-irc -t abduco -A irc dvtm
else
	ssh $* -t abduco -A irc dvtm
fi
