#!/bin/sh

chromium --app=https://netflix.com &

# Wait for Netflix to become the name of the window
while [ ! $(xwininfo -name Netflix 2> /dev/null) ]; do
        sleep 1
done
windowID=$(xwininfo -name Netflix | grep "Window id:" | sed -e 's/^.*id:\s//' -e 's/\s"\w*"$//')
xdg-screensaver suspend $windowID && notify-send Notice "Monitor timeout disabled while netflix is running"
