#!/bin/sh

touchID=$(xinput list | sed -e '/Touchscreen touch/!d' -e 's/^.*\sid=//' -e 's/\s.*$//')
/usr/bin/chromium --profile-directory=Default --app-id=pfpeapihoiogbcmdmnibeplnikfnhoge --touch-devices=$touchID
