#!/bin/sh
# Requiers plex chrome "app"

touchID=$(xinput list | sed -e '/Touchscreen touch/!d' -e 's/^.*\sid=//' -e 's/\s.*$//')
/usr/bin/chromium --profile-directory=Default --app-id=fpniocchabmgenibceglhnfeimmdhdfm --touch-devices=$touchID & chromiumID=$!

# Wait for Plex to become the name of the window
while [ ! "$(xwininfo -name Plex 2> /dev/null)" ] && (ps -p $chromiumID > /dev/null); do
	sleep 1
done
windowID=$(xwininfo -name Plex | grep "Window id:" | sed -e 's/^.*id:\s//' -e 's/\s"\w*"$//')

while (ps -p $chromiumID > /dev/null); do 
	sleep 30
	if (xwininfo -id $windowID | grep "▶" > /dev/null); then
		xdg-screensaver suspend $windowID
	else
		xdg-screensaver resume $windowID
	fi
done
