#!/bin/sh

# Purpose:
# Provide basic, fast manipulation of services outside of a terminal


#TODO
# - implement status, detailed info piped to dmenu
# - make failed list prettier

action=$(dmenu <<EOF
start
stop
restart
enable
enable --now
disable
disable --now
daemon reload
--user start
--user stop
--user restart
--user enable
--user enable --now
--user disable
--user disable --now
--user daemon reload
EOF
)

systemctlArgs="--type service,timer,automount,socket --no-pager"

# if action is status
#if [ "$action" = '--user status' -o "$action" = 'status' ]; then
	# combine output of both --user and --system

[ -z "$action" ] && exit 0 # if no action, quit
if [ -z $(echo $action | sed -e '/--user/d') ]; then # if action contains '--user'
	systemctl --user $systemctlArgs | sed -e '/failed/!d' -e 's/●\s//' > /tmp/dctl
	systemctl --user $systemctlArgs list-unit-files >> /tmp/dctl
	unit=$(dmenu -l 20 </tmp/dctl | sed 's/\s.*$//') # List --user units
	[ -z $unit ] && exit 0 # if no unit, quit
	systemctl $action $unit && notify-send 'dctl - success' "systemctl $action $unit"
else # action for system
	systemctl $systemctlArgs | sed -e '/failed/!d' -e 's/●\s//' > /tmp/dctl
	systemctl $systemctlArgs list-unit-files >> /tmp/dctl
	unit=$(dmenu -l 20 </tmp/dctl | sed 's/\s.*$//') # List --user units
	[ -z $unit ] && exit 0 # if no unit, quit
	sudo -A systemctl $action $unit && notify-send 'dctl - success' "systemctl $action $unit"
fi
