#!/bin/sh

#TODO
# - implement status/enable/etc, pipe output to dmenu
# - option to ask for services or action first
#	asking for service first allows us to print its status seamlessly
# - find a way to indicate failed/running state within the initial list.
# - libnotify?

export SUDO_ASKPASS=~/.bin/askpass.sh
font="inconsolata:size=8"
action=$(echo -e 'start\nstop\nrestart\ndaemon reload\n--user start\n--user stop\n--user restart\n--user daemon reload' | dmenu -fn $font)

# if action is status
#if [ "$action" = '--user status' -o "$action" = 'status' ]; then
	# combine output of both --user and --system

[ -z $action ] && exit 0 # if no action, quit
if [ -z $(echo $action | sed -e '/--user/d') ]; then # if action contains '--user'
	unit=$(systemctl --user list-unit-files --no-pager \
		| grep -P 'enabled|enabled-runtime|linked|linked-runtime|masked|masked-runtime|static|indirect|disabled|generated|transient|bad' \
		| dmenu -fn $font -l 20 | grep -o -P '^.*\.\w+') # List --user units
	[ -z $unit ] && exit 0 # if no unit, quit
	systemctl $action $unit
else # action for system
	unit=$(systemctl list-unit-files --no-pager \
		| grep -P 'enabled|enabled-runtime|linked|linked-runtime|masked|masked-runtime|static|indirect|disabled|generated|transient|bad' \
		| dmenu -fn $font -l 20 | grep -o -P '^.*\.\w+') # List units
	[ -z $unit ] && exit 0 # if no unit, quit
	sudo -A systemctl $action $unit
fi

