#!/bin/sh

# Not meant to replace the lgogdownloader config file

#TODO
# - Accept multiple games
# - Spawn a terminal to monitor download progress?

rows="25" # Number of rows for dmenu output

platform=$(dmenu -p "platform" <<EOF
Linux
Windows
Mac
All
EOF
)
action=$(dmenu <<EOF
download
repair
status
EOF
)

case "$action" in
	download)
		game=$(lgogdownloader --list --platform $platform | dmenu -l $rows -p "select game")
		lgogdownloader --report --platform $platform --download --game $game
		;;
	repair)
		game=$(lgogdownloader --list --platform $platform | dmenu -l $rows -p "select game")
		lgogdownloader --report --platform $platform --repair --game $game
		;;
	status) # Save status file to /tmp and print to dmenu
		echo '*** Please Wait ***' | \
			dmenu  -p 'populating /tmp/gogstatus.log, this could take a while' & dmenuID=$! && \
			lgogdownloader --status > /tmp/gogstatus.log && kill $dmenuID && \
			cat /tmp/gogstatus.log | dmenu -l $rows -p "cat /tmp/gogstatus.log"
		;;
esac
