#!/bin/sh

# Create persistent ssh connection

if [ ! -S /tmp/ssh-cmd ] && [ $DISPLAY ]; then
	SSH_ASKPASS=askpass.sh setsid ssh $* -fMNS /tmp/ssh-cmd
	while ( [ ! -S /tmp/ssh-cmd ] ); do
		sleep 1
	done
elif [ ! -S /tmp/ssh-cmd ]; then
	ssh $* -fMNS /tmp/ssh-cmd
	while ( [ ! -S /tmp/ssh-cmd ] ); do
		sleep 1
	done
fi

if [ $DISPLAY ]; then
	st -c cmdterm -T cmdterm ssh $* -S /tmp/ssh-cmd -tt abduco -A cmd dvtm
else
	ssh $* -S /tmp/ssh-cmd -tt abduco -A cmd dvtm
fi
