#!/bin/sh

while true; do

# Load Average
LOAD=$(awk '{print "", $1, $2, $3}' /proc/loadavg)

# Network Status
WPASTATUS=$(wpa_cli status)
STATE=$(printf '%s\n' $WPASTATUS | awk -F '=' '/wpa_state/ {print $2}')

if [ "$STATE" = 'COMPLETED' ]; then
	# Wifi connection info
	SSID=$(printf '%s\n' $WPASTATUS | awk -F '=' '/^ssid/ {print $2}')
	SIGNALSTR=$(wpa_cli signal_poll | awk -F '=' '/^RSSI=/ {printf $2 "dBm/"} /^LINKSPEED=/ {print $2 "mbps"}')
	NET="${SSID:+$SSID}${SIGNALSTR:+ $SIGNALSTR}"
elif [ -z "$STATE" ]; then
	# Generic info
	DEV=$(ip link | awk -F ': ' '/state UP/ {print $2}')
	NET=$(ip addr show dev $DEV | awk '/inet / {print $7 ":" $2}')
else
	# Wifi attempting to connect info
	NET=$STATE
fi

# Power Status
read -r AC </sys/class/power_supply/AC/online
read -r BAT0 </sys/class/power_supply/BAT0/capacity
read -r BAT1 </sys/class/power_supply/BAT1/capacity
POWER="${BAT1:+$BAT1}${AC:+[$AC]}${BAT0:+$BAT0}"

# Date and Time
CLOCK=$(date '+%b %m/%d %a %H%M')

# Overall output command
xsetroot -name "$LOAD | $NET | $POWER | $CLOCK"

sleep 10

done
