#!/bin/sh

# Pull from imap into maildir
mbsync hotmail

# Remove existing mh structure
rm -rf ~/.mail/mh

# Import maildir into mh

for i in ~/.mail/hotmail/Inbox/new/* ; do
	rcvstore +inbox <"$i"
done

for i in ~/.mail/hotmail/Inbox/cur/* ; do
	rcvstore +inbox <"$i"
done

for i in ~/.mail/hotmail/Archive/new/* ; do
	rcvstore +archive <"$i"
done

for i in ~/.mail/hotmail/Archive/cur/* ; do
	rcvstore +archive <"$i"
done

for i in ~/.mail/hotmail/Junk/new/* ; do
	rcvstore +junk <"$i"
done

for i in ~/.mail/hotmail/Junk/cur/* ; do
	rcvstore +junk <"$i"
done

for i in ~/.mail/hotmail/Drafts/new/* ; do
	rcvstore +netdrafs <"$i"
done

for i in ~/.mail/hotmail/Drafts/cur/* ; do
	rcvstore +netdrafts <"$i"
done

for i in ~/.mail/hotmail/Sent/new/* ; do
	rcvstore +sent <"$i"
done

for i in ~/.mail/hotmail/Sent/cur/* ; do
	rcvstore +sent <"$i"
done

for i in ~/.mail/hotmail/Deleted/new/* ; do
	rcvstore +deleted <"$i"
done

for i in ~/.mail/hotmail/Deleted/cur/* ; do
	rcvstore +deleted <"$i"
done
