#!/bin/sh

# Use dmenu to display recent files from viminfo
# This script may be run from the shell, or within vim
# Add this to your vimrc
#  noremap <C-p> :wv<CR>:e <C-r>=system("mruvim p")<CR><CR>



filename=$(awk '/^'\>'/{ print $2 }' $HOME/.cache/vim/viminfo | uniq | sed "s@~@$HOME@g" | dmenu -i -l 20) || exit

if [ "$1" = "p" ]; then
	echo $filename
else
	vim "$filename"
fi


: <<'Comments'
# Here's the garbage hack I came up with to port this script to msys2 / Windows
# Using slmenu in a new terminal instead of dmenu, and files instead of redirects
# Bugs and mysteries ahead. I don't understand why it works, and I no longer care to

mrufile=$HOME/.cache/vim/mrufile

# If I take this command out of the $(), it won't execute. 
filename=$(awk '/^'\>'/{ print $2 }' $HOME/.cache/vim/viminfo | uniq | sed "s@~@$HOME@g" > $HOME/.cache/vim/mru && mintty -e /usr/bin/sh -c "slmenu -it -l 20 < $HOME/.cache/vim/mru > $mrufile") || exit

# When this script is launched within vim, the above line feeds $mrulefile into $filename BEFORE slmenu is run.
filename=$(cat $mrufile)

if [ "$1" = "p" ]; then
	echo $filename
else
	vim "$filename"
fi
Comments
