#!/bin/sh

# Use dmenu to display recent files from viminfo
# This script may be run from the shell, or within vim
# Add this to your vimrc
#  noremap <C-p> :wv<CR>:e <C-r>=system("mruvim p")<CR><CR>

filename=$(awk '/^'\>'/{ print $2 }' $HOME/.cache/vim/viminfo | uniq | sed "s@~@$HOME@g" | dmenu -i -l 20) || exit

if [ "$1" = "p" ]; then
	echo $filename
else
	vim "$filename"
fi
