#!/bin/sh

# Create a centered floating terminal, cover a % of the screen

# TODO
#  - Figure out if the terminal columns and rows are consistent across resolutions

# Determine width and height
read -r width height << EOF
	$(xrandr | awk '/current/ { print 0+$8, 0+$10 }')
EOF

# Calculate x + y offset
xoff=$(($width / 7))
yoff=$(($height / 10))

st -g 150x45+$xoff+$yoff -c popterm "$@"
