#!/bin/sh

# TODO
# - Accept certificates via dmenu

echo "requesting password via askpass script"
pass=$(daskpass)

case $1 in
	"Local")
		echo $pass | xfreerdp /v:$2 /u:Link /from-stdin /smart-sizing /workarea /gfx /gdi:hw /sound \
			+home-drive +multitouch +gestures +compression +clipboard +fonts -aero -window-drag -menu-anims ;;
	"Remote")
		echo $pass | xfreerdp /v:$2 /u:Link /from-stdin /smart-sizing /workarea /gfx /gdi:hw \
			-home-drive +multitouch +gestures +compression +clipboard +fonts -aero -window-drag -menu-anims ;;
esac
