#!/bin/sh

# TODO
# - Accept certificates via dmenu
# - Libnotify errors
# RDP [example.com[:3389]] [user] [Remote]

[ $# -eq 0 ] && exec $(sed '/RDP/!d' .cache/run_recent | uniq | dmenu -i -l 20) && exit

[ -n "$2" ] && username=$2 || username=$(whoami)
echo "requesting password via askpass script"
pass=$(daskpass)
baseArgs="/smart-sizing /workarea /gfx /gdi:hw +compression +clipboard +fonts -aero -window-drag -menu-anims"

case $3 in
	"Remote")
		otherArgs="-home-drive +multitouch +gestures";;
	*)
		otherArgs="/sound +home-drive +multitouch +gestures";;
esac

xfreerdp /v:$1 /u:$username /from-stdin $baseArgs $otherArgs <<EOF
$pass
EOF
