#!/bin/bash

logfiles=$(find /var/lib/znc/.znc/moddata/log -type f -name "*.log")

function nickmatch {
	case "$@" in
		*"<ircnick>"*)
			# Do not react to own messages!
			;;
		*"ircnick"*)
			notify-send "irc" "$@"
			;;
		*"ircnick"*)
			notify-send "irc" "$@"
			;;
	esac
}

while read i; do nickmatch "$i"; done < <(ssh notify "tail -qfn0 $logfiles")
