#!/bin/bash

#Yes, bash is necessary

function nickmatch {
	case "$*" in
		*"<ircnick>"*)
			# Do not react to own messages!
			;;
		*"ircnick"*)
			notify-send "irc" "$*"
			;;
		*"ircnick"*)
			notify-send "irc" "$*"
			;;
	esac
}

while read i; do nickmatch "$i"; done < <(ssh -i ~/.ssh/tunneler_rsa tunneler@<address> "tail -qfn0 /var/lib/znc/.znc/moddata/log/*/*/*/*")
