#!/bin/zsh

compton -bf -i 0.8 --backend glx --vsync opengl-swc
xmodmap -e "keycode 108 = Super_L"
xmodmap -e "remove mod1 = Super_L"
xmodmap -e "keycode 124 = Insert"
parcellite &
xbindkeys &
eval $(cat ~/.fehbg) &

while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
