" Set a comfy initial window size
set lines=50 columns=100
" Hide mouse while typing
set mousehide
if !has("unix")
	" Set font+size
	set guifont=Courier_New:h10
endif
" Minimal GUI
set guioptions-=T
set guioptions-=m
set guioptions-=r
