" --- Base config --- "

" XDG compliant environment
if has("unix")
	silent !mkdir -p $HOME/.cache/vim
	set directory=$HOME/.cache/vim,~/,/tmp
	set backupdir=$HOME/.cache/vim,~/,/tmp
	set viminfo+=n$HOME/.cache/vim/viminfo
	set runtimepath=$HOME/.config/vim,$HOME/.config/vim/after,$VIM,$VIMRUNTIME
endif
" Enforce UTF-8
set encoding=utf-8
" When no filetype-specific indenting is enabled, new lines inherit above indentation
set autoindent
" Set the command window height to 2 lines, to avoid many cases of having to press <Enter> to continue
set cmdheight=2
" Always display the status line, even if only one window is displayed
set laststatus=2
" Switch on search pattern highlighting.
set hlsearch
" Set enrcyption method to blowfish
set cryptmethod=blowfish2
" Make vim case insensitive...
set ignorecase
" ...Except when we explicitly type a capital
set smartcase
" Jump to matches as you search
set incsearch
" Indicate a line is wrapped with '> '
set showbreak=>\ 
" Indent a wrapped line
set breakindent
" Wrap per word, not character (configured with 'breakat')
set linebreak
" Indent tabs less
set tabstop=4
set shiftwidth=4
" Highlight strings inside C comments
let c_comment_strings=1
" Theme
colorscheme torte
" My own mru solution using dmenu
"noremap <C-p> :wv<CR>:e <C-r>=system("mruvim p")<CR><CR>
" Exit insert mode with jj
inoremap jj <Esc>
" Elevate vim under windows. Update me to use powershell elevation
"noremap <C-e> :mksession! ~/vimfiles/elevate.vim<Return>:silent exec '!elevate.exe ' . v:progname '-S C:/Users/Link/vimfiles/elevate.vim --cmd "let $HOME=''C:\Users\Link\''"'<Return>:q<Return>
" Don't write viminfo while editing an encrypted file
augroup Security
	autocmd vimleavepre * if strlen(&key) | set viminfo= | endif
augroup End

" --- Plugin config --- "

" Vim-plug package manager
call plug#begin()
Plug 'chilicuil/vim-sprunge'
Plug 'paradigm/SkyBison'
Plug 'bling/vim-airline'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'ervandew/supertab'
Plug 'PProvost/vim-ps1'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'tpope/vim-vinegar'
Plug 'Konfekt/FastFold'
call plug#end()
" Call SkyBison with \;
nnoremap <leader>; :<c-u>call SkyBison("")<cr>
" Fuzzy search
let g:skybison_fuzz=2
" Ranger file chooser
"source /usr/share/doc/ranger/examples/vim_file_chooser.vim

" Grey comments, must be declared after Vim-plug
highlight Comment ctermfg=8 guifg=#808080
